# "service" is the name of this project. This will also be added to your AWS resource names.
service: kc-symphony-mobile-music-box-events

provider:
  name: aws
  runtime: nodejs24.x
  environment:
    EVENTS_URL: https://www.kcsymphony.org/concerts-tickets/neighborhood-concerts/
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  domain:
    name: mmbapi.bricemciver.com
    certificateArn: arn:aws:acm:us-east-1:225509306647:certificate/9f15cb6d-0c94-4cc4-a21e-d8d310991b83
    createRoute53Record: false
    apiType: httpApi
    endpointType: regional

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
