# "service" is the name of this project. This will also be added to your AWS resource names.
service: kc-symphony-mobile-music-box-events

provider:
  name: aws
  runtime: nodejs24.x
  environment:
    EVENTS_URL: https://www.kcsymphony.org/concerts-tickets/neighborhood-concerts/
  domain:
    name: ${ssm:/kc-symphony-mobile-music-box-events/domain-name}
    certificateArn: ${ssm:/kc-symphony-mobile-music-box-events/certificate-arn}
    createRoute53Record: false
    apiType: http
    endpointType: regional

build:
  esbuild:
    external:
      - 'jsdom'
    exclude:
      - 'jsdom'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
